version: '3.3'

services:
  discovery-service:
    container_name: "discovery-service"
    build: "./discovery-service"
    expose:
      - "8761"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SERVER_PORT=8761"
      - "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka"
    ports:
      - "8761:8761"
    networks:
      - "microservices-booking-rides-network"
    restart: always

  api-gateway:
    container_name: "api-gateway"
    build: "./api-gateway"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SERVER_PORT=8082"
      - "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka"
    ports:
      - "8082:8082"
    networks:
      - "microservices-booking-rides-network"
    restart: always
    depends_on:
      - discovery-service
    links:
      - discovery-service

  order-service:
    #container_name: "order-service"
    build: "./order-service"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka"
    networks:
    - "microservices-booking-rides-network"
    restart: always
    depends_on:
      - order-service-postgres
      - discovery-service
    links:
      - order-service-postgres
      - discovery-service

  order-service-postgres:
    container_name: order-service-postgres
    image: postgres:latest
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_DB=test"
    networks:
      - "microservices-booking-rides-network"
    ports:
      - "5433:5432"
    volumes:
      - order-service-postgres-volume:/var/lib/postgresql/data

  users-service:
    #container_name: "users-service"
    build: "./users-service"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka"
    networks:
      - "microservices-booking-rides-network"
    restart: always
    depends_on:
      - users-service-postgres
      - discovery-service
    links:
      - users-service-postgres
      - discovery-service

  users-service-postgres:
    container_name: users-service-postgres
    image: postgres:latest
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_DB=test"
    networks:
      - "microservices-booking-rides-network"
    ports:
      - "5434:5432"
    volumes:
      - users-service-postgres-volume:/var/lib/postgresql/data

  driver-matching-service:
    #container_name: "driver-matching-service"
    build: "./driver-matching-service"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka"
    networks:
      - "microservices-booking-rides-network"
    restart: always
    depends_on:
      - driver-matching-service-postgres
      - discovery-service
    links:
      - driver-matching-service-postgres
      - discovery-service

  driver-matching-service-postgres:
    container_name: driver-matching-service-postgres
    image: postgres:latest
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_DB=test"
    networks:
      - "microservices-booking-rides-network"
    ports:
      - "5435:5432"
    volumes:
        - driver-matching-service-postgres-volume:/var/lib/postgresql/data

networks:
  microservices-booking-rides-network:
    driver: bridge

volumes:
  order-service-postgres-volume:
  users-service-postgres-volume:
  driver-matching-service-postgres-volume: